#spring.datasource.url: jdbc:h2:file:./camunda-h2-database
camunda.bpm.admin-user:
  id: hari
  password: hari5679


#logging:
#  level:
camunda:
  bpm:
    default-serialization-format: application/json
#    root: debug