<<<<<<< HEAD
spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda.bpm.admin-user:
  id: hari
  password: hari
#logging:
#  level:
=======
#spring.datasource.url: jdbc:h2:file:./camunda-h2-database
camunda.bpm.admin-user:
  id: hari
  password: hari5679
#logging:
#  level:
>>>>>>> f13bbabc373b7ae220dcb6ef85e16acf21ad8740
#    root: debug